lr: 0.0001
batch_size: 1024
num_workers: 2
epochs: 100
device: mps
dataset:
  # point this to the directory you've cloned under, e.g. <user_directory>/transformer_playground/data/othello_championship
  data_root: /Users/salman/projects/transformer_playground/data/othello_championship
  seq_len: 100
model:
  n_blocks: 2
  n_heads: 2
  d_head: 128
  d_model: 256
  d_mlp: 512
  d_vocab: 60
  context_length: 100